server:
  port: 8080
#  servlet:
#    context-path: /

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: MySQL
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

# 七牛云存储
oss:
  qiniu:
    domain: http://qm9jv5yvy.hn-bkt.clouddn.com # 访问域名(默认使用七牛云测试域名)qm9jv5yvy.hn-bkt.clouddn.com
    accessKey: SAMlj6hUfAl_yyaOyaL1keo_zMv9iMNPYifl2JxI # 公钥
    secretKey: e7L9cgtG0PeLyN-i98sBFvkgUUvhTbAok9B31RjE # 私钥
    bucketName: reservation  #存储空间名称


#  security:
#    user:
#      name: zxj
#      password: 123456
#      roles: admin
#****//// security configure file method







